kind: pipeline
name: default

steps:
- name: test
  image: python:3.6.7-alpine3.8
  environment:
    APP_ENV: Testing
  commands:
    - pip -i https://mirrors.aliyun.com/pypi/simple/ install -r requirements.txt
    - python3 -m pytest

services:
  - name: database
    image: mongo:4-xenial