version: '3'

services:
  pyweb:
    build: .
    ports:
      - "9000:5000"
    environment:
      - APP_ENV=Production
    # volumes 参数把当前目录挂载到容器的 /code
    # docker-compose 的配置中才支持相对路径的挂载
    volumes:
      - .:/code
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:4-xenial
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: